TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += rknmntr.db
DB += RIKEN_TEMP_CALC.db
DB += test_PSU_PVs.db
DB += test_block_curr_PVs.db

#=======================================
include $(TOP)/configure/RULES
