TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += rknmntr.db
DATA += rknmntr.proto

#=======================================
include $(TOP)/configure/RULES
