TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += RIKEN_TEMP_CALC.db
#TODO add sim and disable records
#=======================================
include $(TOP)/configure/RULES
